USE techub;

CREATE TABLE USER(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(100)
);

CREATE TABLE PRODUCT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_DESCRIPTION VARCHAR(100),
    PRICE NUMERIC(20,2)
);

CREATE TABLE USER_ORDER (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_ID INTEGER REFERENCES USER (ID),
    ORDER_DATE TIMESTAMP,
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ORDER_ITEM (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_ORDER_ID INTEGER REFERENCES USER_ORDER (ID),
    USER_PRODUCT_ID INTEGER REFERENCES USER_ORDER (ID),
    QUANTITY INTEGER
);